gh release edit private-0.6.1 --notes "See diff with previous release." <NUL
gh release edit private-0.7.1 --notes "See diff with previous release." <NUL
gh release edit private-0.8.0 --notes "See diff with previous release." <NUL
gh release edit private-0.8.1 --notes "See diff with previous release." <NUL
gh release edit private-0.8.2 --notes "See diff with previous release." <NUL
gh release edit private-0.8.3 --notes "See diff with previous release." <NUL
gh release edit private-0.8.4 --notes "See diff with previous release." <NUL
gh release edit private-0.8.4.1 --notes "See diff with previous release." <NUL
gh release edit private-0.8.4.2 --notes "See diff with previous release." <NUL
gh release edit private-0.8.5 --notes "See diff with previous release." <NUL
gh release edit private-0.9.0 --notes "See diff with previous release." <NUL
gh release edit private-0.9.1 --notes "See diff with previous release." <NUL
gh release edit private-2.3.3.10-19-26.1 --notes "See diff with previous release." <NUL
gh release edit private-3.0.1.10-19-26.0 --notes "See diff with previous release." <NUL
gh release edit private-3.0.1.10-19-26.2 --notes "See diff with previous release." <NUL
gh release edit private-3.0.1.10-19-26.3 --notes "See diff with previous release." <NUL
gh release edit private-3.0.1.10-19-26.4 --notes "See diff with previous release." <NUL
gh release edit private-3.1.3.14-27-27.0 --notes "See diff with previous release." <NUL
gh release edit private-3.1.3.14-27-27.1 --notes "See diff with previous release." <NUL
gh release edit private-3.1.3.14-27-27.2 --notes "See diff with previous release." <NUL
gh release edit private-3.1.4.14-27-27.0 --notes "See diff with previous release." <NUL
gh release edit private-3.1.4.14-27-27.1 --notes "See diff with previous release." <NUL
gh release edit private-3.1.4.14-27-27.2 --notes "See diff with previous release." <NUL
gh release edit private-3.1.4.14-27-27.3 --notes "See diff with previous release." <NUL
gh release edit private-3.1.4.14-28-28.0 --notes "See diff with previous release." <NUL
gh release edit private-3.1.4.14-28-28.1 --notes "See diff with previous release." <NUL
gh release edit private-3.1.4.14-28-28.2 --notes "See diff with previous release." <NUL
gh release edit private-3.2.1.14-28-28.0 --notes "See diff with previous release." <NUL
gh release edit private-3.2.1.14-28-28.1 --notes "See diff with previous release." <NUL
gh release edit private-3.2.1.14-28-28.2 --notes "See diff with previous release." <NUL
gh release edit private-3.2.1.14-28-28.3 --notes "See diff with previous release." <NUL
gh release edit private-3.3.2.14-28-28.0 --notes "See diff with previous release." <NUL
gh release edit private-3.3.2.14-28-28.1 --notes "See diff with previous release." <NUL
gh release edit private-3.3.2.14-28-28.2 --notes "See diff with previous release." <NUL
gh release edit private-3.4.2.14-28-28.0 --notes "See diff with previous release." <NUL
gh release edit private-3.4.2.14-29-29.0 --notes "See diff with previous release." <NUL
gh release edit private-3.4.2.14-29-29.1 --notes "See diff with previous release." <NUL
gh release edit private-3.5.4.14-29-29.0 --notes "See diff with previous release." <NUL
gh release edit private-3.6.4.14-29-29.0 --notes "See diff with previous release." <NUL
gh release edit private-4.0.2.14-29-29.0 --notes "See diff with previous release." <NUL
gh release edit private-4.0.2.14-29-29.1 --notes "See diff with previous release." <NUL
gh release edit private-4.0.2.14-29-29.2 --notes "See diff with previous release." <NUL
gh release edit private-4.1.0.14-29-29.0 --notes "See diff with previous release." <NUL
gh release edit private-4.1.1.14-29-29.0 --notes "See diff with previous release." <NUL
gh release edit private-4.1.1.14-29-29.1 --notes "See diff with previous release." <NUL
