[libraries]
kotlin-gradle-v18x = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version = "1.8.22" }
kotlin-gradle-v19x = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version = "1.9.25" }
