name: Check Gradle and AGP combinations
on: [push]
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      # see https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
      TEST_GRADLE_VERSION: ${{ matrix.gradle }}
      ANDROID_PLUGIN_VERSION: ${{ matrix.agp }}
      ANDROID_BUILD_TOOLS_VERSION: ${{ matrix.build-tools }}
      # see android-all_kinds/build.gradle for more info
      ANDROID_INSTANT_API_LEVEL: ${{ matrix.instant-api }}
    steps:
      - run: echo "Running in response to a ${{ github.event_name }} event."
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Check out ${{ github.ref }} branch in ${{ github.repository }} repository
        uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # To run specific test, replace `check tests` with `:quality:test --tests '*.HtmlReportTaskTest.runs on lints'`
      - name: ${{ matrix.name }}
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          check tests
          -PverboseReports
          -Pnet.twisterrob.test.android.pluginVersion=$ANDROID_PLUGIN_VERSION
          -Pnet.twisterrob.gradle.runner.gradleVersion=$TEST_GRADLE_VERSION
    strategy:
      matrix:
        #gradle: []
        #agp: []
        #build-tools: []
        #instant-api: []
        include:
          - name: "Android Gradle Plugin 4.2.x, Gradle 6.7.1+"
            gradle: 6.7.1
            agp: 4.2.0
            build-tools: 30.0.2
            instant-api: 30
          - name: "Android Gradle Plugin 4.2.x, Gradle 6.x"
            gradle: 6.9
            agp: 4.2.0
            build-tools: 30.0.2
            instant-api: 30
